"""Shared product and governance constants."""

PRODUCTS = (
    "WORKING_CAPITAL_LOAN",
    "POS_MERCHANT_ACQUIRING",
    "BUSINESS_CREDIT_CARD",
    "PAYROLL_SERVICES",
    "CASH_MANAGEMENT",
    "TRADE_FINANCE",
    "TERM_DEPOSIT",
    "FX_RISK_MANAGEMENT",
)

CREDIT_PRODUCTS = {
    "WORKING_CAPITAL_LOAN",
    "BUSINESS_CREDIT_CARD",
    "TRADE_FINANCE",
}

CONTROLLED_SYNTHETIC = "CONTROLLED_SYNTHETIC"
PUBLIC_REFERENCE = "PUBLIC_REFERENCE"
DERIVED_ANALYTICS = "DERIVED_ANALYTICS"
